name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get install -y minify
    
    - name: Compile un-compressed version
      run: make

    - name: Compile & Minimify 
      run: make min
      
    - name: Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            build/bib-list.css
            build/bib-list.js
            build/bib-list.min.css
            build/bib-list.min.js
